Update hamonikr-min

diff --git a/usr/local/bin/hamonikr-min b/usr/local/bin/hamonikr-min
--- a/usr/local/bin/hamonikr-min
+++ b/usr/local/bin/hamonikr-min
@@ -17,65 +17,44 @@ log() {
     exec 1>&3 3>&-
 }
 
+process_file() {
+    local file_path=$1
+    local action=$2
+
+    if [ ! -f ${file_path} ]; then
+        log "[ERROR] Could not find ${file_path} file"
+        return
+    fi
+
+    while IFS= read -r line || [[ -n "$line" ]]; do
+        line=$(echo $line | xargs)  # Trim leading/trailing whitespace
+        if [[ -n $line && ! $line =~ ^# ]]; then
+            if [ "$action" = "kill" ]; then
+                killall $line
+                [ $? -eq 0 ] && log "killed $line"
+            elif [ "$action" = "disable" ]; then
+                if [ -f $HOME/.config/autostart/$line ]; then
+                    mv $HOME/.config/autostart/$line $HOME/.config/autostart/$line.norun
+                    [ $? -eq 0 ] && log "Disabled $line"
+                fi
+            elif [ "$action" = "enable" ]; then
+                if [ -f $HOME/.config/autostart/$line.norun ]; then
+                    mv $HOME/.config/autostart/$line.norun $HOME/.config/autostart/$line
+                    [ $? -eq 0 ] && log "Enabled $line"
+                fi
+            fi
+        fi
+    done < ${file_path}
+}
+
 case "$1" in
     start)
-        #if [ -x /usr/local/bin/hamonikr-theme-setting ]; then
-        #    rm -f $HOME/.hamonikr/theme/hamonikr-theme-setting.done
-        #    /usr/local/bin/hamonikr-theme-setting winstyle
-        #fi
-        
-        killps="/usr/share/hamonikr/hamonikr-min/killps"
-        if [ -f ${killps} ]; then
-            IFS=$'\n' read -d '' -r -a lines < ${killps}
-            ## get item count using ${lines[@]} ##
-            for process in "${lines[@]}"
-            do
-                if [[ ! ${process} =~ "#" ]]; then
-                    killall ${process}
-                    [ $? -eq 0 ] && log "killed ${process}" 
-                fi
-            done
-        else
-            log "[ERROR] Could not fount ${killps} file"
-        fi
-
-        killapps="/usr/share/hamonikr/hamonikr-min/killapps"
-        if [ -f ${killapps} ]; then
-            IFS=$'\n' read -d '' -r -a lines < ${killapps}
-
-            for apps in "${lines[@]}"
-            do
-                if [[ ! ${apps} =~ "#" ]]; then
-                    if [ -f $HOME/.config/autostart/${apps} ]; then
-                        mv $HOME/.config/autostart/${apps} $HOME/.config/autostart/${apps}.norun
-                        [ $? -eq 0 ] && log "Disabled ${apps}"
-                    fi
-                     
-                fi
-            done
-        else
-            log "[ERROR] Could not fount ${killapps} file"
-        fi
-      ;;
+        process_file "/usr/share/hamonikr/hamonikr-min/killps" "kill"
+        process_file "/usr/share/hamonikr/hamonikr-min/killapps" "disable"
+        ;;
     stop)
-        killapps="/usr/share/hamonikr/hamonikr-min/killapps"
-        if [ -f ${killapps} ]; then
-            IFS=$'\n' read -d '' -r -a lines < ${killapps}
-
-            for apps in "${lines[@]}"
-            do
-                if [[ ! ${apps} =~ "#" ]]; then
-                    if [ -f $HOME/.config/autostart/${apps}.norun ]; then
-                        mv $HOME/.config/autostart/${apps}.norun $HOME/.config/autostart/${apps}
-                        [ $? -eq 0 ] && log "Enabled ${apps}"
-                    fi
-                     
-                fi
-            done
-        else
-            log "[ERROR] Could not fount ${killapps} file"
-        fi
-      ;;
+        process_file "/usr/share/hamonikr/hamonikr-min/killapps" "enable"
+        ;;
     *)
-      ;;
+        ;;
 esac
